version: '3.8'

# .env is loaded by default.

services:
  backend:
    image: ndeamador/game-affinity-project-server
    container_name: gap-backend
    # build: .
    command: npm start
    ports:
      - '4000:4000'
    depends_on:
      - database
      - redis

  database:
    image: postgres
    container_name: gap-postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped #  keep the container running unless it’s stopped. With "always" the stopped container is started after reboot for example.
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT

  redis:
    image: redis
    container_name: gap-redis
    # command: redis-server --requirepass $REDIS_PASSWORD # Just a workaround to add password to redis.
    ports:
      - 6379:6379

  # watchtower automates updating images of running containers: https://github.com/containrrr/watchtower
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: gap-watchtower
