# name: Release DevOps with Docker

# # https://github.com/marketplace/actions/build-and-push-docker-images

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       # Checkout to the repository (the actions don't actually need this since they use the repository context anyway)
#       - uses: actions/checkout@v2

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       # Push to docker hub
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: ndeamador/game-affinity-project-server:latest
